# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 989ae51c87e2da20c5b4e93d5a83ea838a9b7112f0ee28edfad3d62194fa48ed02de29f88706955d45175042a84187c37756413b9b1c20cef42251a5ce18d56a

test:
  secret_key_base: d3efdeb8078034664da9d61aaebeffcb90106a524871a4fe38fdf14cbde9aae5907eb2b5ac8dde35eb482fe2e7b4b1b552ba79aa827eebc3d8883456912397dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
